dependencies {
    implementation 'com.zaxxer:HikariCP:6.3.0'
    implementation 'com.h2database:h2:2.3.232'
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.17'
    implementation 'org.apache.commons:commons-pool2:2.12.1'
}

tasks.register('runDemo', JavaExec) {
    group = 'application'
    javaLauncher = javaToolchains.launcherFor(java.toolchain)
    classpath = sourceSets.main.runtimeClasspath
    mainClass = providers.gradleProperty('demo').orElse('poolstudy.semaphore.SemaphoreDemo')
}
